chore: update workflow node12 to node16

diff --git a/.github/workflows/updated.yaml b/.github/workflows/updated.yaml
--- a/.github/workflows/updated.yaml
+++ b/.github/workflows/updated.yaml
@@ -20,18 +20,14 @@ jobs:
       - name: Checkout
         uses: actions/checkout@v2
       - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v1
-        #uses: christopher-dG/gh-aws-oidc@v1
+        uses: aws-actions/configure-aws-credentials@v1-node16
         with:
-          #role-arn: ${{ secrets.GITHUBACTION_ROLE }}
           role-to-assume: ${{ secrets.GITHUBACTION_ROLE }}
           role-session-name: github-workflow-rolesession
           aws-region: us-east-1
-          #region: us-east-1
       - name: Run Update AWS Managed Policies
         id: build 
-        run: ./check && echo "::set-output name=conclusion::success" || echo
-          "::set-output name=conclusion::failure"
+        run: ./check && echo "conclusion=success" >> $GITHUB_OUTPUT || echo "conclusion=failure" >> $GITHUB_OUTPUT
       - name: Upload update.txt
         uses: actions/upload-artifact@v2
         with:
@@ -77,7 +73,7 @@ jobs:
           }}/.upgrade.tmp.patch || echo "Skipping."
       - name: Create Pull Request
         id: create-pr
-        uses: peter-evans/create-pull-request@v3
+        uses: peter-evans/create-pull-request@v4.2.1
         with:
           token: ${{ secrets.AUTOMATION_GITHUB_TOKEN }}
           commit-message: >-
